### ISSUE TITLE
Sample application demonstrating usage. 

### ISSUE THREAD

**Issue by kernelfreak** [ttddyy/spring-social-evernote#1]
Hi,

I am quite interested in Spring-Social-evernote as I plan to integrate it into our Spring-MVC application. Unfortunately, I cannot find any sample usage, or how to consume this framework. 

Do you have any examples which you tried with your framework. Can you kindly post a few of them. Thank you. 

My apologies if I opened an issue for this, but didn't knew how to contact you. 

Regards,
Akshay S

**Comment by ttddyy** [comment]
Hi Akshay,

Thanks for the interest.

About sample usage, I wrote a post to spring blog before:
https://spring.io/blog/2015/06/15/introducing-spring-social-evernote

Also, I made an app to provide restful API for evernote using spring-social-evernote.
You may find its source code for reference as well:
https://github.com/ttddyy/evernote-rest-webapp

The core is `EvernoteTemplate`. Once it's created with auth info, you can get _~Operations_ which can perform Notebook, or User operations such as `NoteStoreOperation`, `UserStoreOperation`.

Thanks,

**Comment by kernelfreak** [comment]
Thank you. I have already finished this task. But I will keep an eye incase I need again.
